@startuml
'https://plantuml.com/class-diagram

interface Adaptee {
    specRequest1()
    specRequest2()
}
note right of Adaptee:需要适配的类

interface Target {
    request1()
    request2()
}
note right of Target:这是客户所期待的接口。目标可以是接口、抽象类或是具体的类

class Adapter {
    Adaptee adaptee
    request1()
    request2()
}
note bottom of Adapter:通过在内部包装一个Adaptee对象，把源接口转换成目标接口


Adapter .> Adaptee : adaptee

Target <|.. Adapter

class AppClient {
    Target target
}
AppClient -> Target : target

@enduml